[twitch]
# Your username on Twitch.
username = ""
# The streamer's name.
channel = ""
# The IRC channel you'd like to connect to.
server = "irc.chat.twitch.tv"
# OAuth token that authenticates you into Twitch. Acquired through https://twitchapps.com/tmi/.
token = ""

[terminal]
# The delay in milliseconds between terminal updates.
tick_delay = 30
# The maximum amount of messages to be stored.
maximum_messages = 150
# The file path to log to.
log_file = ""
# The state the application will start in.
start_state = "dashboard"

[storage]
# If previous channels switched to should be tracked.
channels = false
# If previous username mentions should be tracked.
mentions = false

[filters]
# If filters should be enabled at all.
enabled = false
# If the regex filters should be reversed.
reversed = false

[frontend]
# If the time and date is to be shown.
date_shown = true
# The format of the date and time outputs. Formats can be found at https://strftime.org/.
date_format = "%a %b %e %T %Y"
# If the username should be shown.
username_shown = true
# The color palette for the username column: pastel (default), vibrant, warm, cool.
palette = "pastel"
# Show title with time and channel.
title_shown = true
# The amount of space between the chat window and the terminal border.
margin = 0
# Show twitch badges next to usernames.
badges = false
# The theme of the frontend, dark (default), or light.
theme = "dark"
# If the user's name appears in chat, highlight it.
username_highlight = true
# If there should be state tabs shown on the bottom of the terminal
state_tabs = false
# The shape of the cursor, block (default), underscore, or line.
cursor_shape = "block"
# If the cursor should be blinking in input boxes.
blinking_cursor = false
# If the scrolling should be inverted.
inverted_scrolling = false
# If scroll offset should be shown (bottom right of chat window).
show_scroll_offset = false
# Show twitch emotes.
twitch_emotes = false
# Show betterttv emotes.
betterttv_emotes = false
# Show 7tv emotes.
seventv_emotes = false
# Array of channel names as strings to be displayed at start screen.
start_screen_channels = []
# What the style of the border should be.
border_type = "plain"
# If the usernames should be aligned to the right instead of the left.
right_align_usernames = false
