name: Building & Testing

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os:
          - { prettyname: Windows, fullname: windows-latest }
          - { prettyname: macOS, fullname: macos-latest }
          - { prettyname: Linux, fullname: ubuntu-latest }

        threadingMode: [ 'SingleThread', 'MultiThreaded' ]

    timeout-minutes: 60

    runs-on: ${{matrix.os.fullname}}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
